### ISSUE TITLE
Pricing for Plastic SCM license holders

### ISSUE THREAD

**Issue by viceroypenguin** [gmasterscm/ama#10]
Similar to Issue #3 : If I currently have a license for Plastic SCM, will that include a copy of GMaster, or will I need to have a separate license for each?

**Comment by Devonthemoon** [comment]
Plastic SCM does not include a copy of GMaster. GMaster is git client for developers or teams using git as their source control system. Not sure why you would see that combination attractive. Please, can you tell us?

Plastic SCM is our Distributed Version Control System. It is complete and our flagship product, and will continue to be innovative and differential from git-like products: security, audit logs, native support for large binary files, distributed locking, full managed cloud service, fast network protocols and file system (Jet), horizontal and vertical scalability, workflow and UI for artists, designers and VR/AR developers (Plastic Gluon), full diff and merge tool, including Semantic support, Git interoperability (GitSync and GitServer), and a never ending backlog of new features and ideas.
