### ISSUE TITLE
Remotes

### ISSUE THREAD

**Issue by rthomson83** [gmasterscm/ama#5]
If a branch is deleted as a result of a pull request and is removed on the remote it doesn't seem to auto prune these in the app when running a fetch.

**Comment by rubarax** [comment]
The current behavior for the fetch/pull operations is to use the configured prune option value. 

You can set it as follows:
`git config remote.origin.prune true`

At some point, we will allow to configure this prune option from the GUI!

**Comment by rthomson83** [comment]
Yeah that'll work, thanks for clearing that up!
