### ISSUE TITLE
UX for Viewing a commit

### ISSUE THREAD

**Issue by viceroypenguin** [gmasterscm/ama#9]
Currently, you have three icons at the top right for switching between views with the commit. 
![image](https://user-images.githubusercontent.com/1992555/30337586-963bcc98-979d-11e7-8a1e-7a98cd57d494.png)

Currently, the only way to close the new window from the third icon is to restore the window to half size and then click the left icon. The secondary window for commit details needs to support ctrl-f4 and have an X at the top right to support closing the window. Otherwise, if you're limited to a single monitor, say on a laptop while traveling, it's difficult to get back to the main window.

**Comment by psantosl** [comment]
We discussed this internally (sorry for not coming back to you earlier) and we'll try to find out a decent solution :) Thanks!
